name: Build & Release Desktop App

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build_and_publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish Electron Application
        run: npm run release:electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}